### ISSUE TITLE
Usage of :: to refer to functions

### ISSUE THREAD

**Issue by matiasandina** [zmzhang/airPLS_R#1]
Hi,
Thanks for this implementation, very useful. I was just wondering if you could add the `::` when referring to functions that are overwriting functions from base R. In particular in `WhittakerSmooth`, here's the implementation I got working without importing the package. I am happy to submit a pull request if preferred
 
```
WhittakerSmooth <- function(x,w,lambda,differences=1) {
  x=matrix(x,nrow = 1, ncol=length(x))
  L=length(x)
  E=Matrix::spMatrix(L,L,i=seq(1,L),j=seq(1,L),rep(1,L))
  D=as(Matrix::diff(E,1,differences),"dgCMatrix")
  W=as(Matrix::spMatrix(L,L,i=seq(1,L),j=seq(1,L),w),"dgCMatrix")
  background=Matrix::solve((W+lambda*Matrix::t(D)%*%D),Matrix::t((w*x)));
  return(as.vector(background))
}

```

**Comment by zmzhang** [comment]
Hi @matiasandina,
Thanks for your feedback.
Very happy that airPLS is useful for your research. Adding :: when referring to functions that override the base R is an excellent suggestion. Please submit a pull request and I will merge it in time.

Regards
Zhimin

**Comment by zmzhang** [comment]
#2 pull request merged.
